const DELAY = global.bot.config.halimaw.replyDelay;

const REPLIES = [
  // ENGLISH — ROASTS
  "Bro really thought that was necessary 💀",
  "Confidence... delusion... UNMATCHED 😭",
  "Say less, lost brain cells reading that 💀",
  "You typed ALL THAT just to embarrass yourself? 😬",
  "Main character energy but plot is MID 🗑️",
  "Who hurt you? That hurt ALL of us 💔",
  "Please stop before they file a restraining order 🚩",
  "You really said that out loud... PERMANENTLY 🤦",
  "Audacity LOUD, intelligence ON MUTE 🔇",
  "This is WHY mute buttons exist �",
  "Chose violence against the English language 💥",
  "Not mad, just disappointed 😔",
  "Aged like milk left in the sun 🥛→🤢",
  "Grammar teachers crying somewhere rn 😭",
  "Energy: I peaked in high school 🎓",
  "Dropped that like it was fire — it WASN'T 🔥❌",
  "Chat was peaceful until YOU arrived ☮️→💥",
  "Log off for everyone's mental health 🧠",
  "That was a bold... TERRIBLE choice 😬",
  "Taking notes on how NOT to communicate 📝",
  "Keyboard called — wants its letters back ⌨️",
  "Silence is golden, your message is bronze 🥉",
  "Explain wrong? Not enough bandwidth 📉",
  "Every type = 1 angel loses brain cells 😇",
  "Not wrong, just NOT TRYING 💅",
  "Not hot take — COLD MESS 🥶",
  "Some questions better unanswered — YOURS ❓→🚫",
  "Not everyone has good judgment 🤷",
  "Message empty like cloud ☁️",
  "Confidence 100 / Sense 0 💯",
  "Aged faster than milk in summer ☀️",
  "Bravery = knowing when to SHUT UP 🤐",
  "Not every thought needs AIRTIME 📢",
  "Almost making sense... ALMOST 😐",
  "Filed under: WHY THOUGH? 📂",
  "Silence is okay, REALLY 🤫",
  "Volume ≠ Value 🔊≠💎",
  "Thinking hard? Don't hurt yourself 🤕",
  "That's not a take, that's a MISTAKE ❌",
  "Agreeing with you = BOTH WRONG 🤝❌",
  "Instructions on shampoo bottles exist for a reason 🧴",
  "Would argue, don't speak nonsense 🗣️",
  "Loud not clear — like broken speaker 🔊",
  "Floor is yours — GIVE IT BACK 🧹",
  "Not laughing AT you, laughing WITH CONCERN 😬",
  "Mystery — no solution found 🔍",
  "Bold typing choice, I respect the audacity 🙌",
  "We all have moments — THIS IS YOURS 📸",
  "Say less = mean less, try it ✅",
  "Contribution ZERO, confidence INFINITE ♾️",
  "Making noise NOT history 📜",
  "Sound ≠ Thought 🗣️≠🧠",
  "Reply properly? Nonsense takes effort 💤",
  "Keep talking — enjoying the example 📚",
  "Words free, patience NOT ⏳",
  "Skipped the thinking part huh? 🧠→❌",
  "Not every opinion needs airing 🧺",
  "Brave... but WRONG 🧭",
  "Don't ask what you mean, don't wanna know 🚫",
  "Why can't we have nice quiet chats? 🥺",
  "Question mark with ZERO answers ❓",
  "Not helping the conversation 📉",
  "Some shine — you just REFLECT ✨",
  "Not a point, just a POST 📱",
  "Don't type just because YOU CAN ⌨️",
  "Emotional damage 🗡️",
  "Skill issue 🎮",
  "Touch grass 🌿",
  "Go touch grass I BEG 🌿🙏",
  "Your opinion has been logged and ignored ✅",
  "I'd agree but then we'd both be wrong 🤝",
  "That's a special way to be wrong 🎨",
  "Brain buffering... ⏳",
  "Error 404: Common sense not found ❌",
  "Your mouth is writing checks your brain can't cash 💸",
  "This is why we can't have nice things 🥺",
  "Blink twice if you need help 🫣",
  "W I D E 🐸",
  "Average enjoyer detected 📡",
  "Peak fiction 📖",
  "L + Ratio + Didn't Ask 💀",
  "Cope harder 🧠",
  "Skill issue + L + Cry about it 🥲",
  "Nobody asked but okay 💅",
  "Delusion levels: CRITICAL 🚨",
  "You're doing great sweetie 🍭 — never change",
  "The audacity is STAGGERING 🤯",
  "Keep it up, I'm taking notes 📝",
  "Source? 📖",
  "Trust me bro is not a source 🤦",
  "Reality check: FAILED ❌",
  "You're brave for that I'll give you that 🏅",
  "Bold of you to assume I care 🤷",
  "Not my circus, not my monkeys 🎪",
  "Idk man sounds like a YOU problem 🤷‍♂️",
  "I'm not saying you're wrong... but I'm NOT NOT saying it 🤔",
  "Interesting take... never said GOOD 🤔",
  "You're really going with that? Alright 🤷",
  "Okay and? 🤔",
  "Who asked? 💀",
  "Didn't ask, don't care ✅",
  "My notifications regret this 📱",
  "This chat will recover 🩹",
  "One day you'll look back and CRINGE 🤢",
  "Cringe detected 📡",
  "Bro is fighting for his LIFE in the comments 💀",
  "And that's on what? 💅",
  "I smell a main character complex 🕵️",
  "Sir this is a Wendy's 🍔",
  "Be so fr rn 🧢",
  "Real recognize real and you look FAMILIAR 🤡",
  "Pick a struggle fr 💀",
  "Not you thinking that mattered 😭",
  "Your keyboard deserves an apology ⌨️🙏",
  "How do I unfriend a thought? 🤔",
  "That hurt to read ngl 😭",
  "I'm just here to watch 🤿",
  
  // TAGALOG — TARANTADO
  "Akala mo may kwenta? Wala naman 💀",
  "Kalmahan mo, hindi karera 🏃‍♂️",
  "Ang tapang sa chat, tahimik sa personal 🤫",
  "Oras mo sayang diyan ⏳",
  "Bakit parang galit? Inom ka tubig 💧",
  "Tumigil ka bago mahalin sarili mong salita 😬",
  "Pahinga ka muna, nakakapagod ka 🥱",
  "Ang lakas ng loob, kulang sa laman 💪→🧠",
  "Magsalita lang kung may sasabihin 🗣️",
  "Paulit-ulit walang saysay 🔁",
  "Bakit sumagot kung di nakaintindi? 🤦",
  "Mag-isip bago mag-send — LIBRE NAMAN 🧠",
  "Hindi lahat dapat sinasabi 🤐",
  "Ang gulo parang buhay mo 🫠",
  "Huwag mag-alala, di ka naman pinapakinggan 🎧",
  "Ang taas lipad, bagsak sa laman 🪂",
  "Sana kasing talino ng bilis mag-type ⌨️",
  "Ang dami sinabi, wala naman napatunayan 📉",
  "Tumahimik ka, mas mukha kang matalino 🤫",
  "Ikaw yung tipong magaling sa chat, duwag sa labas 🚪",
  "Wag kang umasta parang kilala kita 🤨",
  "Hindi naman kailangan sumagot sa LAHAT eh 🤐",
  "Buhay ka ba? Mukhang robot kasi 🤖",
  "Isipin mo muna bago ka magsalita, sayang oras 🕐",
  "Mas malinaw pa ang ulap kaysa sinabi mo ☁️",
  "Bakit ka galit? Inaway ka ba ng katotohanan? 🔨",
  "Huwag mong piliting magmukhang tama kung mali naman 🤦",
  "Ang lakas magsalita, pero wala namang laman 🧱",
  "Pahinga ka na, pagod na kaming makinig 🥱",
  "Kung wala kang sasabihing maganda — manahimik ka 🤫",
  "Hindi ka special, wag umasta parang isa ka ✨",
  "Galingan mo naman, kulang sa effort 📉",
  "Isang utak sana mauna 😭",
  "Bida-bida ka masyado eh 🤡",
  "Kung alam mo lang kung gaano ka katawa-tawa 😂",
  "Huwag kang mag-alala, makakalimutan din kita agad 🧠",
  "Ang ingay, parang walang buhay 🤫",
  "Maganda sana kung may sense din 💡",
  "Sana may laman yung sinabi mo 📦",
  "Pwede bang tumahimik ka muna? 🥺",
  "Hindi lahat ng gusto mo, pwedeng sabihin 🤐",
  "Ang bilis mag-send, ang bagal mag-isip 🐢",
  "Kung kaya mong itama, gawin mo — kung hindi, tumahimik ka 🤫",
  "Mukhang mahirap maging ikaw ngayon 🥲",
  "Wag kang umasta parang eksperto 🤓",
  "Ang daming alam, wala namang napatunayan 🎓❌",
  "Mas tahimik na mundo kung wala ka 😌",
  "Ikaw yung dahilan kung bakit may mute button 🔇",
  "Sana nagtanong ka muna bago magsalita 🤔",
  "Hindi naman kailangan sumagot eh 🤐",
  "Ang tapang mo kasi nasa screen ka lang 📱",
  "Lalabas ka ba? Wag na, nakakatakot ka eh 😬",
  "Bakit parang lagi kang tama? Kasi mali ka 🤦",
  "Mag-isip ka muna, hindi ka nagmamadali ⏳",
  "Ang gulo-gulo, parang utak mo 🧠",
  "Wag mong piliting maging tama ang mali 🔄",
  "Kung hindi ka makakatulong, wag kang makasagabal 🚧",
  "Mas mabuti pang manahimik kaysa magsalita ng walang saysay 🤐",
  "Ikaw yung nagpapababa ng IQ ng GC natin 📉",
  "Sana matuto kang makinig, hindi puro salita 👂",
  "Wag kang magmalinis, alam ko kung sino ka 🧹",
  "Ang daming sinabi, wala namang patunay 📝",
  "Hindi ka naman kawalan eh 😌",
  "Pwede bang ibalik na yung dating ikaw? Yung tahimik 🥺",
  "Bakit kailangan ikaw laging tama? 🤨",
  "Maganda sana kung totoo din ✨",
  "Ang bilis magsalita, mabagal umintindi 🐌",
  "Huwag kang mag-alala, di ka naman pinapansin 👀",
  "Kung kaya mong manahimik, gawin mo na 🤫",
  "Wag kang mag-isip masyado, masasaktan ka 🤕",
  "Ang lakas ng loob mo, wala namang pinagbabasehan 🪑",
  "Sana magbago ka — sa ibang GC naman 🥺",
  "Isipin mo muna bago mag-send, sayang oras ng lahat ⏰",
  "Ang daming alam, wala namang naiintindihan 🤦‍♂️",
  "Tumahimik ka, mas maganda ang ganito 😌",
  "Hindi lahat ng tanong, kailangan sagutin 🤔",
  "Ang gulo-gulo mo, parang walang direksyon 🧭",
  "Wag kang magmalakas, nasa chat ka lang 📱",
  "Kung mali, aminin — hindi yung laging tama 🤷",
  "Mas mabuti pang mali pero tapat kaysa tama pero peke 🤥",
  "Ang daming sinabi, hindi naman nakatulong 📉",
  "Sana matuto kang tumanggap ng pagkakamali 📝",
  "Wag kang mag-alala, lilipas din ito 🌊",
  "Ikaw yung dahilan kung bakit kailangan magingat sa salita 🗣️",
  "Ang lakas magsalita, mahina ang loob 🐥",
  "Hindi ka naman kailangan dito eh 😌",
  "Sana matuto kang makinig sa iba 👂",
  "Bakit parang lagi kang nagtuturo? 📚",
  "Ang daming sinabi, wala namang kabuluhan 🚮",
  "Tumahimik ka na, pagod na kaming makinig 🥱",
  "Wag kang mag-astang kilala mo ako 🤨",
  "Kung wala kang sasabihing maganda, manahimik ka 🤐",
  "Ang bilis magsalita, mabagal mag-isip 🐢",
  "Hindi lahat ng gusto mo, pwedeng sabihin 🤐",
  "Sana magbago ka — para sa sarili mo rin 💚",
  "Ang daming alam, wala namang napatunayan 🎓❌",
  "Mas tahimik na mundo kung wala ka 😌",
  "Ikaw yung nagpapababa ng antas ng usapan 📉",
  "Sana matuto kang mag-isip bago magsalita 🧠",
  "Wag kang magmalinis, lahat tayo may pagkukulang 🧹",
  "Ang daming sinabi, wala namang patunay 📝",
  "Hindi ka naman kawalan eh 😌",
  "Pwede bang ibalik na yung dating ikaw? Yung tahimik 🥺",
  "Bakit kailangan ikaw laging tama? 🤨",
  "Maganda sana kung totoo din ✨",
  "Ang bilis magsalita, mabagal umintindi 🐌",
  "Huwag kang mag-alala, di ka naman pinapansin 👀",
  "Kung kaya mong manahimik, gawin mo na 🤫",
  "Wag kang mag-isip masyado, masasaktan ka 🤕",
  "Ang lakas ng loob mo, wala namang pinagbabasehan 🪑",
  "Sana magbago ka — sa ibang GC naman 🥺"
];

module.exports.config = {
  name: "halimaw",
  version: "3.1.0-MANY-REPLIES",
  description: "150+ Replies — Auto-Responder"
};

module.exports.run = async function ({ api, event, react, stats }) {
  const { threadID, messageID } = event;

  react("haha", messageID);

  setTimeout(() => {
    const reply = REPLIES[Math.floor(Math.random() * REPLIES.length)];
    api.sendMessage(reply, threadID);
    stats.repliesSent++;
    stats.lastReply = new Date().toLocaleString("en-PH", { timeZone: "Asia/Manila" });
  }, DELAY);
};
